/*
 * changeps.java
 *
 * Created on __DATE__, __TIME__
 */

package com.demo;

import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.lang.model.type.PrimitiveType;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;

import org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper;

import com.demo.db.DbUtil;

import domain.User;

import util.ObjUtil;

/**
 *
 * @author  __USER__
 */
public class changeps extends javax.swing.JFrame {

	/** Creates new form changeps */
	public changeps() {
		initComponents();
		this.setLocationRelativeTo(null);
		accountText.setText("0411180311");
		passwordTxt.setText("123456");
		passwod2Txt.setText("12345678");
		try {
			org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper.launchBeautyEyeLNF();
			UIManager.put("RootPane.setupButtonVisible", false);
			BeautyEyeLNFHelper.frameBorderStyle = BeautyEyeLNFHelper.frameBorderStyle.osLookAndFeelDecorated;

		} catch (Exception e) {
			// TODO: handle exception
		}
		Font font = new Font("Dialog", Font.PLAIN, 12);
		java.util.Enumeration keys = UIManager.getDefaults().keys();
		while (keys.hasMoreElements()) {
			Object key = keys.nextElement();
			Object value = UIManager.get(key);
			if (value instanceof javax.swing.plaf.FontUIResource)
				;
			UIManager.put(font, value);
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		accountText = new javax.swing.JTextField();
		passwordTxt = new javax.swing.JPasswordField();
		jButton1 = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		passwod2Txt = new javax.swing.JPasswordField();
		jButton2 = new javax.swing.JButton();
		jLabel5 = new javax.swing.JLabel();
		label1 = new java.awt.Label();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel2.setFont(new java.awt.Font("楷体", 0, 18));
		jLabel2.setText("\u5bc6\u7801");

		jLabel3.setFont(new java.awt.Font("楷体", 0, 18));
		jLabel3.setText("\u8d26\u53f7");

		accountText.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				accountTextActionPerformed(evt);
			}
		});

		passwordTxt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				actionPerformed(evt);
			}
		});

		jButton1.setFont(new java.awt.Font("隶书", 3, 18));
		jButton1.setText("\u786e\u8ba4\u4fee\u6539");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel4.setFont(new java.awt.Font("楷体", 0, 18));
		jLabel4.setText("\u786e\u8ba4\u5bc6\u7801");

		passwod2Txt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				actionPerformed(evt);
			}
		});

		jButton2.setFont(new java.awt.Font("隶书", 3, 18));
		jButton2.setText("\u8fd4\u56de");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jLabel5.setFont(new java.awt.Font("华文行楷", 3, 48));
		jLabel5.setForeground(new java.awt.Color(51, 51, 255));
		jLabel5.setText("\u4fee\u6539\u5bc6\u7801\u754c\u9762");

		label1.setFont(new java.awt.Font("方正粗黑宋简体", 3, 12));
		label1.setText("\u5f00\u53d1\u8005\uff1a\u8c2d\u831c\u5347");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel4)
																						.addComponent(
																								jLabel3,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								46,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addGap(
																												25,
																												25,
																												25)
																										.addComponent(
																												accountText,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												289,
																												Short.MAX_VALUE))
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								layout
																										.createSequentialGroup()
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												passwod2Txt,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												289,
																												javax.swing.GroupLayout.PREFERRED_SIZE))))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				86,
																				86,
																				86)
																		.addComponent(
																				jButton1)
																		.addGap(
																				85,
																				85,
																				85)
																		.addComponent(
																				jButton2))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				52,
																				52,
																				52)
																		.addComponent(
																				jLabel5)))
										.addContainerGap())
						.addGroup(
								layout.createSequentialGroup().addComponent(
										label1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										92, Short.MAX_VALUE).addGap(324, 324,
										324))
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jLabel2,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												54, Short.MAX_VALUE)
										.addGap(43, 43, 43)
										.addComponent(
												passwordTxt,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												289, Short.MAX_VALUE)
										.addContainerGap()));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addGap(34, 34, 34)
										.addComponent(jLabel5)
										.addGap(33, 33, 33)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabel3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																19,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																accountText,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabel2,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																28,
																Short.MAX_VALUE)
														.addComponent(
																passwordTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(11, 11, 11)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jLabel4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																36,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																passwod2Txt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton1)
														.addComponent(jButton2))
										.addGap(5, 5, 5)
										.addComponent(
												label1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												28,
												javax.swing.GroupLayout.PREFERRED_SIZE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		turn tu = new turn();
		tu.setVisible(true);
		this.dispose();
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String account = accountText.getText().trim();
		String passwd = passwordTxt.getText().trim();
		String passwd2 = passwod2Txt.getText().trim();
		if (!(ObjUtil.isEmpty(account) || ObjUtil.isEmpty(passwd) || ObjUtil
				.isEmpty(passwd2))) {
			if (!passwd.equals(passwd2)) {
				JOptionPane.showMessageDialog(null, "两次密码不相同");
				accountText.setText("");
				passwordTxt.setText("");
				passwod2Txt.setText("");
				return;
			}

			User user = new User(null, null, passwd, account);
			Connection conn = null;
			PreparedStatement ps = null;
			String sql = "update users set passwd=? where account=?";
			//User user2=new User();

			try {
				conn = DbUtil.getConnection();
				ps = conn.prepareStatement(sql);
				ps.setString(1, passwd);
				ps.setString(2, account);
				int success = ps.executeUpdate();
				//判断与原密码是否相同
				checkps(account, passwd);
				if (success > 0) {

					JOptionPane.showMessageDialog(null, "密码修改成功");
					turn tu = new turn();
					tu.setVisible(true);
					this.dispose();
				} else {
					JOptionPane.showMessageDialog(null, "密码修改失败,请输入正确账号");
					return;
				}

			} catch (SQLException e) {
				e.printStackTrace();
				// TODO Auto-generated catch block
				e.printStackTrace();
			} finally {

			}
		} else {
			JOptionPane.showMessageDialog(null, "注意输入框不能为空");
			accountText.setText("");
			passwordTxt.setText("");
			passwod2Txt.setText("");
			return;
		}

	}

	public void checkps(String account, String passwd) {
		Connection conn2 = null;
		PreparedStatement ps2 = null;
		ResultSet rs2 = null;
		String sql2 = "select passwd from users where account=?";
		try {
			conn2 = DbUtil.getConnection();
			ps2 = conn2.prepareStatement(sql2);
			ps2.setString(1, account);
			rs2 = ps2.executeQuery();

			while (rs2.next()) {
				String passwdc = rs2.getString(account);
				System.out.println(passwdc);
				if (passwd.equals(passwdc))
					;
				JOptionPane.showMessageDialog(null, "不能与原密码一致");
			}
		} catch (SQLException e1) {
			// TODO Auto-generated catch block

		} finally {
			DbUtil.release(conn2, ps2, rs2);

		}

	}

	void passwd2TxtActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	public static void passwordTxtActionPerformed(String args[]) {

	}

	private void accountTextActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new changeps().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTextField accountText;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private java.awt.Label label1;
	private javax.swing.JPasswordField passwod2Txt;
	private javax.swing.JPasswordField passwordTxt;
	// End of variables declaration//GEN-END:variables

}