/*
 * departmentUI.java
 *
 * Created on __DATE__, __TIME__
 */

package com.demo;

import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

import org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper;

import util.ObjUtil;

import com.demo.db.DbUtil;

import domain.Userinfo;
import domain.department;

/**
 *
 * @author  __USER__
 */
public class departmentUI extends javax.swing.JFrame {

	/** Creates new form departmentUI */
	public departmentUI() {
		initComponents();
		flushtable();
		this.setLocationRelativeTo(null);
		try {
			org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper.launchBeautyEyeLNF();
			UIManager.put("RootPane.setupButtonVisible", false);
			BeautyEyeLNFHelper.frameBorderStyle = BeautyEyeLNFHelper.frameBorderStyle.osLookAndFeelDecorated;

		} catch (Exception e) {
			// TODO: handle exception
		}
		Font font = new Font("Dialog", Font.PLAIN, 12);
		java.util.Enumeration keys = UIManager.getDefaults().keys();
		while (keys.hasMoreElements()) {
			Object key = keys.nextElement();
			Object value = UIManager.get(key);
			if (value instanceof javax.swing.plaf.FontUIResource)
				;
			UIManager.put(font, value);
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		label5 = new java.awt.Label();
		schoolTxt = new java.awt.TextField();
		label2 = new java.awt.Label();
		acTxt = new java.awt.TextField();
		label3 = new java.awt.Label();
		accodeTxt = new java.awt.TextField();
		label1 = new java.awt.Label();
		checkTxt = new java.awt.TextField();
		button1 = new java.awt.Button();
		jScrollPane1 = new javax.swing.JScrollPane();
		yxTable = new javax.swing.JTable();
		button2 = new java.awt.Button();
		button3 = new java.awt.Button();
		button4 = new java.awt.Button();
		label7 = new java.awt.Label();
		compusTxt = new java.awt.TextField();
		button5 = new java.awt.Button();
		label4 = new java.awt.Label();
		button6 = new java.awt.Button();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		label5.setFont(new java.awt.Font("楷体", 1, 18));
		label5.setName("yuan");
		label5.setText("\u5b66\u6821\u4ee3\u7801");

		schoolTxt.setFont(new java.awt.Font("楷体", 1, 18));
		schoolTxt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				schoolTxtActionPerformed(evt);
			}
		});

		label2.setFont(new java.awt.Font("楷体", 1, 18));
		label2.setName("yuan");
		label2.setText("\u5b66\u9662\u540d\u79f0");

		acTxt.setFont(new java.awt.Font("楷体", 1, 18));
		acTxt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				actionPerformed(evt);
			}
		});

		label3.setFont(new java.awt.Font("楷体", 1, 18));
		label3.setName("yuan");
		label3.setText("\u5b66\u9662\u4ee3\u7801");

		accodeTxt.setFont(new java.awt.Font("楷体", 1, 18));
		accodeTxt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				accodeTxtActionPerformed(evt);
			}
		});

		label1.setFont(new java.awt.Font("楷体", 1, 18));
		label1.setText("\u67e5\u8be2\u9662\u6821\u540d\u79f0");

		checkTxt.setFont(new java.awt.Font("楷体", 1, 18));
		checkTxt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				checkTxtActionPerformed(evt);
			}
		});

		button1.setFont(new java.awt.Font("华文行楷", 3, 18));
		button1.setLabel("\u67e5\u8be2");
		button1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				button1ActionPerformed(evt);
			}
		});

		yxTable.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				}, new String[] { "学院名称", "学院代码", "学校代码", "校区代码" }) {
			Class[] types = new Class[] { java.lang.String.class,
					java.lang.String.class, java.lang.String.class,
					java.lang.String.class };

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}
		});
		yxTable.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				yxTableMousePressed(evt);
			}
		});
		jScrollPane1.setViewportView(yxTable);

		button2.setFont(new java.awt.Font("华文楷体", 3, 18));
		button2.setLabel("\u589e\u52a0");
		button2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				button2ActionPerformed(evt);
			}
		});

		button3.setFont(new java.awt.Font("华文楷体", 3, 18));
		button3.setLabel("\u4fee\u6539");
		button3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				button3ActionPerformed(evt);
			}
		});

		button4.setFont(new java.awt.Font("华文楷体", 3, 18));
		button4.setLabel("\u5220\u9664");
		button4.setName("\u5220\u9664");
		button4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				button4ActionPerformed(evt);
			}
		});

		label7.setFont(new java.awt.Font("楷体", 1, 18));
		label7.setName("yuan");
		label7.setText("\u6821\u533a\u4ee3\u7801");

		compusTxt.setFont(new java.awt.Font("楷体", 1, 18));
		compusTxt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				compusTxtActionPerformed(evt);
			}
		});

		button5.setFont(new java.awt.Font("华文楷体", 3, 18));
		button5.setLabel("\u8fd4\u56de");
		button5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				button5ActionPerformed(evt);
			}
		});

		label4.setFont(new java.awt.Font("楷体", 3, 48));
		label4.setText("\u9662\u6821\u4fe1\u606f\u754c\u9762");

		button6.setFont(new java.awt.Font("华文行楷", 3, 18));
		button6.setLabel("\u8fd4\u56de\u67e5\u8be2");
		button6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				button6ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(70, 70, 70)
										.addComponent(
												button2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(93, 93, 93)
										.addComponent(
												button3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(123, 123, 123)
										.addComponent(
												button4,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												85, Short.MAX_VALUE)
										.addComponent(
												button5,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(176, Short.MAX_VALUE))
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(60, 60, 60)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				423,
																				423,
																				423)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												label7,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												compusTxt,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												90,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												label3,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												accodeTxt,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												90,
																												javax.swing.GroupLayout.PREFERRED_SIZE))))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				label2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				acTxt,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				90,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				label5,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				schoolTxt,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				90,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(100, Short.MAX_VALUE))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup().addContainerGap(
										238, Short.MAX_VALUE).addComponent(
										label4,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(215, 215, 215))
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(40, 40, 40)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				41,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				label1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				60,
																				60,
																				60)
																		.addComponent(
																				checkTxt,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				130,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				88,
																				88,
																				88)
																		.addComponent(
																				button1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				71,
																				71,
																				71)
																		.addComponent(
																				button6,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				23,
																				23,
																				23))
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																639,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(46, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				label4,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				68,
																				Short.MAX_VALUE)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addGroup(
																								layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																										.addComponent(
																												checkTxt,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addComponent(
																												label1,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addComponent(
																								button1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				button6,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(27, 27, 27)
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												174,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(28, 28, 28)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																acTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																label2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																accodeTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																label3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(36, 36, 36)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								schoolTxt,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								label5,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(
																				17,
																				17,
																				17))
														.addComponent(
																compusTxt,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																label7,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(29, 29, 29)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																button2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																button4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																button3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																button5,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(20, 20, 20)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void button6ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		flushtable();
	}

	private void checkTxtActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void button5ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		turn tu = new turn();
		tu.setVisible(true);
		this.dispose();
	}

	//查询
	private void button1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String ac = this.checkTxt.getText();
		if (!(ObjUtil.isEmpty(ac))) {
			cxflushtable(ac);
		}

		else
			JOptionPane.showMessageDialog(null, "查询失败，输入框不能为空");
	}

	//删除
	private void button4ActionPerformed(java.awt.event.ActionEvent evt) {
		String academy = acTxt.getText().trim();
		String accode = accodeTxt.getText().trim();
		String school = schoolTxt.getText().trim();
		String compus = compusTxt.getText().trim();

		if (ObjUtil.isEmpty(academy) || ObjUtil.isEmpty(accode)
				|| ObjUtil.isEmpty(school) || ObjUtil.isEmpty(compus)) {

			return;
		}
		Connection conn = null;
		PreparedStatement ps = null;
		String sql = "delete from department where academy=?";

		try {
			conn = DbUtil.getConnection();
			ps = conn.prepareStatement(sql);

			ps.setString(1, academy);

			int success = ps.executeUpdate();
			if (success > 0) {
				JOptionPane.showMessageDialog(null, "删除成功");
			} else
				JOptionPane.showMessageDialog(null, "删除失败");

		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally {
			DbUtil.release(conn, ps, null);

		}
		flushtable();
	}

	//修改
	private void button3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String academy = acTxt.getText().trim();
		String accode = accodeTxt.getText().trim();
		String school = schoolTxt.getText().trim();
		String compus = compusTxt.getText().trim();

		if (ObjUtil.isEmpty(academy) || ObjUtil.isEmpty(accode)
				|| ObjUtil.isEmpty(school) || ObjUtil.isEmpty(compus)) {

			return;
		}
		Connection conn = null;
		PreparedStatement ps = null;
		String sql = "update department set academycode=?,schoolcode=?,compuscode=? where academy=?";

		try {
			conn = DbUtil.getConnection();
			ps = conn.prepareStatement(sql);
			ps.setString(4, academy);
			ps.setString(1, accode);
			ps.setString(2, school);
			ps.setString(3, compus);
			int success = ps.executeUpdate();
			if (success > 0) {
				JOptionPane.showMessageDialog(null, "修改成功");
			} else
				JOptionPane.showMessageDialog(null, "修改失败");

		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally {
			DbUtil.release(conn, ps, null);

		}
		flushtable();
	}

	//添加
	private void button2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String academy = acTxt.getText().trim();
		String accode = accodeTxt.getText().trim();
		String school = schoolTxt.getText().trim();
		String compus = compusTxt.getText().trim();

		if (ObjUtil.isEmpty(academy) || ObjUtil.isEmpty(accode)
				|| ObjUtil.isEmpty(school) || ObjUtil.isEmpty(compus)) {

			return;
		}
		Connection conn = null;
		PreparedStatement ps = null;
		String sql = "insert into department (academy,academycode,schoolcode,compuscode) values(?,?,?,?)";

		try {
			conn = DbUtil.getConnection();
			ps = conn.prepareStatement(sql);
			ps.setString(1, academy);
			ps.setString(2, accode);
			ps.setString(3, school);
			ps.setString(4, compus);
			int success = ps.executeUpdate();
			if (success > 0) {
				JOptionPane.showMessageDialog(null, "添加成功");
			} else
				JOptionPane.showMessageDialog(null, "添加失败");

		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally {
			DbUtil.release(conn, ps, null);

		}
		flushtable();

	}

	private void compusTxtActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	//刷新
	private void yxTableMousePressed(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		int academy = 0;
		int academycode = 1;
		int schoolcode = 2;
		int compuscode = 3;

		//选中在哪行
		int row = this.yxTable.getSelectedRow();
		//一个多少列
		int cols = this.yxTable.getColumnCount();
		String[] strs = new String[4];
		for (int i = 0; i < cols; i++) {
			strs[i] = (String) this.yxTable.getValueAt(row, i);
		}

		department Department = new department(null, strs[academy],
				strs[academycode], strs[schoolcode], strs[compuscode]);
		acTxt.setText(Department.getAcademy());
		accodeTxt.setText(Department.getAcademycode());
		schoolTxt.setText(Department.getSchoolcode());
		compusTxt.setText(Department.getCompuscode());

	}

	private void flushtable() {
		Connection conn = null;
		PreparedStatement ps = null;
		ResultSet rs = null;
		String sql = "select * from department";
		try {
			conn = DbUtil.getConnection();
			ps = conn.prepareStatement(sql);
			rs = ps.executeQuery();
			ArrayList<department> departments = new ArrayList<department>();
			while (rs.next()) {
				String academy = rs.getString("academy");
				String academycode = rs.getString("academycode");
				String schoolcode = rs.getString("schoolcode");
				String compuscode = rs.getString("compuscode");
				department depa = new department(null, academy, academycode,
						schoolcode, compuscode);
				departments.add(depa);

			}
			DefaultTableModel dtm = (DefaultTableModel) this.yxTable.getModel();
			dtm.setRowCount(0);
			if (departments.size() > 0) {
				for (department department : departments) {
					Vector vector = new Vector();
					vector.add(department.getAcademy());
					vector.add(department.getAcademycode());
					vector.add(department.getSchoolcode());
					vector.add(department.getCompuscode());

					dtm.addRow(vector);

				}

			}

		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally {
			DbUtil.release(conn, ps, rs);

		}
	}

	private void cxflushtable(String ac) {
		Connection conn = null;
		PreparedStatement ps = null;
		ResultSet rs = null;
		String sql = "select * from department where academy like ? ";
		try {
			conn = DbUtil.getConnection();
			ps = conn.prepareStatement(sql);
			ps.setString(1, "%" + ac + "%");
			rs = ps.executeQuery();
			ArrayList<department> departments = new ArrayList<department>();
			while (rs.next()) {
				String academy = rs.getString("academy");
				String academycode = rs.getString("academycode");
				String schoolcode = rs.getString("schoolcode");
				String compuscode = rs.getString("compuscode");
				department depa = new department(null, academy, academycode,
						schoolcode, compuscode);
				departments.add(depa);

			}
			DefaultTableModel dtm = (DefaultTableModel) this.yxTable.getModel();
			dtm.setRowCount(0);
			if (departments.size() > 0) {
				for (department department : departments) {
					Vector vector = new Vector();
					vector.add(department.getAcademy());
					vector.add(department.getAcademycode());
					vector.add(department.getSchoolcode());
					vector.add(department.getCompuscode());

					dtm.addRow(vector);

				}

			}

		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally {
			DbUtil.release(conn, ps, rs);

		}
	}

	void accodeTxtActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	// TODO add your handling code here:

	void schoolTxtActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new departmentUI().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private java.awt.TextField acTxt;
	private java.awt.TextField accodeTxt;
	private java.awt.Button button1;
	private java.awt.Button button2;
	private java.awt.Button button3;
	private java.awt.Button button4;
	private java.awt.Button button5;
	private java.awt.Button button6;
	private java.awt.TextField checkTxt;
	private java.awt.TextField compusTxt;
	private javax.swing.JScrollPane jScrollPane1;
	private java.awt.Label label1;
	private java.awt.Label label2;
	private java.awt.Label label3;
	private java.awt.Label label4;
	private java.awt.Label label5;
	private java.awt.Label label7;
	private java.awt.TextField schoolTxt;
	private javax.swing.JTable yxTable;
	// End of variables declaration//GEN-END:variables

}