/*
 * loginUI.java
 *
 * Created on __DATE__, __TIME__
 */

package com.demo;

import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;
import javax.swing.UIManager;

import org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper;

import util.ObjUtil;

import com.demo.db.DbUtil;

import domain.User;

/**
 *
 * @author  __USER__
 */
public class loginUI extends javax.swing.JFrame {

	/** Creates new form loginUI */
	public loginUI() {
		initComponents();
		this.setLocationRelativeTo(null);
		accountText.setText("0411180310");
		passwordText.setText("123");
		try {
			org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper.launchBeautyEyeLNF();
			UIManager.put("RootPane.setupButtonVisible", false);
			BeautyEyeLNFHelper.frameBorderStyle = BeautyEyeLNFHelper.frameBorderStyle.osLookAndFeelDecorated;

		} catch (Exception e) {
			// TODO: handle exception
		}
		Font font = new Font("Dialog", Font.PLAIN, 12);
		java.util.Enumeration keys = UIManager.getDefaults().keys();
		while (keys.hasMoreElements()) {
			Object key = keys.nextElement();
			Object value = UIManager.get(key);
			if (value instanceof javax.swing.plaf.FontUIResource)
				;
			UIManager.put(font, value);
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		accountText = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		logBut = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();
		logBut1 = new javax.swing.JButton();
		label1 = new java.awt.Label();
		logBut2 = new javax.swing.JButton();
		passwordText = new javax.swing.JPasswordField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		accountText.setFont(new java.awt.Font("楷体", 2, 24));
		accountText.setForeground(new java.awt.Color(102, 102, 102));
		accountText.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				actionPerformed(evt);
			}
		});

		jLabel1.setFont(new java.awt.Font("楷体", 2, 24));
		jLabel1.setForeground(new java.awt.Color(102, 102, 102));
		jLabel1.setText("\u8d26\u53f7");

		jLabel2.setFont(new java.awt.Font("楷体", 2, 24));
		jLabel2.setForeground(new java.awt.Color(102, 102, 102));
		jLabel2.setText("\u5bc6\u7801");

		logBut.setFont(new java.awt.Font("华文隶书", 3, 18));
		logBut.setForeground(new java.awt.Color(102, 102, 102));
		logBut.setText("\u767b\u5f55");
		logBut.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					logButActionPerformed(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jLabel3.setFont(new java.awt.Font("楷体", 3, 48));
		jLabel3.setForeground(new java.awt.Color(153, 153, 0));
		jLabel3.setText("\u6821\u5bf9\u540d\u518c\u7cfb\u7edf");

		logBut1.setFont(new java.awt.Font("华文隶书", 3, 18));
		logBut1.setForeground(new java.awt.Color(102, 102, 102));
		logBut1.setText("\u6ce8\u518c");
		logBut1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				logBut1ActionPerformed(evt);
			}
		});

		label1.setFont(new java.awt.Font("方正粗黑宋简体", 3, 12));
		label1.setText("\u5f00\u53d1\u8005\uff1a\u8c2d\u831c\u5347");

		logBut2.setFont(new java.awt.Font("华文隶书", 3, 18));
		logBut2.setForeground(new java.awt.Color(102, 102, 102));
		logBut2.setText("\u5173\u95ed");
		logBut2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				logBut2ActionPerformed(evt);
			}
		});

		passwordText.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				passwordTextActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout.createSequentialGroup().addComponent(
										label1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										123, Short.MAX_VALUE).addGap(494, 494,
										494))
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				71,
																				71,
																				71)
																		.addComponent(
																				logBut))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				86,
																				86,
																				86)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel2)
																						.addComponent(
																								jLabel1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								68,
																								javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jLabel3,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												364,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addGap(
																												95,
																												95,
																												95)
																										.addComponent(
																												logBut1)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																												136,
																												Short.MAX_VALUE)
																										.addComponent(
																												logBut2)))
																		.addGap(
																				90,
																				90,
																				90))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																layout
																		.createSequentialGroup()
																		.addGap(
																				64,
																				64,
																				64)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								accountText,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								247,
																								Short.MAX_VALUE)
																						.addComponent(
																								passwordText,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								247,
																								Short.MAX_VALUE))
																		.addGap(
																				152,
																				152,
																				152)))));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(8, 8, 8)
										.addComponent(
												jLabel3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												64,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(36, 36, 36)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				27,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				29,
																				29,
																				29)
																		.addComponent(
																				jLabel2))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				accountText,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				31,
																				31,
																				31)
																		.addComponent(
																				passwordText,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				36,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(42, 42, 42)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(logBut)
														.addComponent(logBut1)
														.addComponent(logBut2))
										.addGap(58, 58, 58)
										.addComponent(
												label1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												28,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void passwordTextActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code h
	}

	private void logBut2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.dispose();
	
	}

	private void logBut1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Register ru = new Register(this, true);
		ru.setVisible(true);

	}

	private void logButActionPerformed(java.awt.event.ActionEvent evt)
			throws SQLException {
		// TODO add your handling code here:
		String account = accountText.getText().trim();//获取账号内容
		String passwd = passwordText.getText().trim();//获取密码内容
		//System.out.print(account + "--->" + passwd);
		if (ObjUtil.isEmpty(account) || ObjUtil.isEmpty(passwd)) {
			JOptionPane.showMessageDialog(null, "注意输入框不能为空");
			passwordText.setText("");
			accountText.setText("");
			return;
		}

		User user = new User(null, null, passwd, account);
		Connection conn = null;
		PreparedStatement ps = null;
		ResultSet rs = null;

		try {
			conn = DbUtil.getConnection();
			String sql = "select * from users where account=? ";

			ps = conn.prepareStatement(sql);
			ps.setString(1, user.getAccount());
			rs = ps.executeQuery();
			User queryUser = null;
			while (rs.next()) {
				queryUser = new User();
				String username = rs.getString("uname");
				String acc = rs.getString("account");
				String pass = rs.getString("passwd");
				queryUser.setUname(username);
				queryUser.setAccount(acc);
				queryUser.setPasswd(pass);
			}

			if (queryUser != null) {
				if (queryUser.getPasswd().equals(user.getPasswd())) {
					//System.out.print("登陆成功");
					JOptionPane.showMessageDialog(null, "登录成功");

					//update(dtFieldxh.getText());
					//跳转信息界面
					//					informationUI inf = new informationUI();
					//					inf.setVisible(true);
					//					this.dispose();
					turn t = new turn();
					t.setVisible(true);
				

				}

			} else {
				JOptionPane.showMessageDialog(null, "查无此人！");

			}
		} catch (SQLException e) {
			e.printStackTrace();
		} finally {
			DbUtil.release(conn, ps, rs);
		}
		this.dispose();
		
	}

	/*private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Register ru = new Register(this, true);
		ru.setVisible(true);

	}*/

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new loginUI().setVisible(true);
			}
		});

	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTextField accountText;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private java.awt.Label label1;
	private javax.swing.JButton logBut;
	private javax.swing.JButton logBut1;
	private javax.swing.JButton logBut2;
	private javax.swing.JPasswordField passwordText;
	// End of variables declaration//GEN-END:variables

}