/*
 * Register.java
 *
 * Created on __DATE__, __TIME__
 */

package com.demo;

import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import javax.swing.JOptionPane;
import javax.swing.UIManager;

import org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper;

import com.demo.db.DbUtil;

import domain.User;

import util.DbTest;
import util.ObjUtil;

/**
 *
 * @author  __USER__
 */
public class Register extends javax.swing.JDialog {

	/** Creates new form Register */
	public Register(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		this.setLocationRelativeTo(null);
		try {
			org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper.launchBeautyEyeLNF();
			UIManager.put("RootPane.setupButtonVisible", false);
			BeautyEyeLNFHelper.frameBorderStyle = BeautyEyeLNFHelper.frameBorderStyle.osLookAndFeelDecorated;

		} catch (Exception e) {
			// TODO: handle exception
		}
		Font font = new Font("Dialog", Font.PLAIN, 12);
		java.util.Enumeration keys = UIManager.getDefaults().keys();
		while (keys.hasMoreElements()) {
			Object key = keys.nextElement();
			Object value = UIManager.get(key);
			if (value instanceof javax.swing.plaf.FontUIResource)
				;
			UIManager.put(font, value);
		}
		nameTxt.setText("²ÁÐìÀ¤");
		accountText.setText("0411183135");
		passwodTxt.setText("123456");
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		nameTxt = new javax.swing.JTextField();
		passwodTxt = new javax.swing.JPasswordField();
		jLabel3 = new javax.swing.JLabel();
		accountText = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		label1 = new java.awt.Label();
		jButton2 = new javax.swing.JButton();
		jLabel5 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jLabel1.setText("\u59d3\u540d");

		jLabel2.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jLabel2.setText("\u5bc6\u7801");

		nameTxt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				nameTxtActionPerformed(evt);
			}
		});

		passwodTxt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				passwodTxtActionPerformed(evt);
			}
		});

		jLabel3.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jLabel3.setText("\u8d26\u53f7");

		accountText.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				accountTextActionPerformed(evt);
			}
		});

		jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 3, 14));
		jButton1.setText("\u6ce8\u518c");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton1ActionPerformed(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		label1.setFont(new java.awt.Font("·½Õý´ÖºÚËÎ¼òÌå", 3, 12));
		label1.setText("\u5f00\u53d1\u8005\uff1a\u8c2d\u831c\u5347");

		jButton2.setFont(new java.awt.Font("Microsoft YaHei UI", 3, 14));
		jButton2.setText("\u8fd4\u56de");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jLabel5.setFont(new java.awt.Font("»ªÎÄÐÐ¿¬", 3, 48));
		jLabel5.setForeground(new java.awt.Color(51, 51, 255));
		jLabel5.setText("\u6ce8\u518c\u8d26\u53f7\u754c\u9762");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(37, 37, 37)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel2,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				95,
																				Short.MAX_VALUE)
																		.addGap(
																				311,
																				311,
																				311))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel1,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												36,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(
																												38,
																												38,
																												38)
																										.addComponent(
																												nameTxt,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												263,
																												Short.MAX_VALUE))
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel3,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												36,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(
																												38,
																												38,
																												38)
																										.addGroup(
																												layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																accountText,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																263,
																																Short.MAX_VALUE)
																														.addComponent(
																																passwodTxt,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																263,
																																Short.MAX_VALUE)
																														.addGroup(
																																layout
																																		.createSequentialGroup()
																																		.addGap(
																																				7,
																																				7,
																																				7)
																																		.addComponent(
																																				jButton1)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																																				99,
																																				Short.MAX_VALUE)
																																		.addComponent(
																																				jButton2)
																																		.addGap(
																																				35,
																																				35,
																																				35)))))
																		.addGap(
																				69,
																				69,
																				69))))
						.addGroup(
								layout.createSequentialGroup().addComponent(
										label1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										92, Short.MAX_VALUE).addGap(351, 351,
										351)).addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup().addContainerGap(
										83, Short.MAX_VALUE).addComponent(
										jLabel5).addGap(54, 54, 54)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel5)
										.addGap(26, 26, 26)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																nameTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabel1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																19,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(41, 41, 41)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabel3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																19,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																accountText,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(42, 42, 42)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				passwodTxt,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				22,
																				22,
																				22))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel2,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				28,
																				Short.MAX_VALUE)
																		.addGap(
																				18,
																				18,
																				18)))
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				82,
																				82,
																				82)
																		.addComponent(
																				label1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				28,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				27,
																				27,
																				27)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jButton1)
																						.addComponent(
																								jButton2))))
										.addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void passwodTxtActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.dispose();
		loginUI log = new loginUI();
		log.setVisible(true);
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
			throws SQLException {
		// TODO add your handling code here:
		String uname = nameTxt.getText().trim();
		String account = accountText.getText().trim();
		String passwd = new String(passwodTxt.getPassword()).trim();
		if (ObjUtil.isEmpty(uname) || ObjUtil.isEmpty(account)
				|| ObjUtil.isEmpty(passwd)) {
			JOptionPane.showMessageDialog(null, "×¢ÒâÊäÈë¿ò²»ÄÜÎª¿Õ");
			nameTxt.setText("");
			accountText.setText("");
			return;
		}
		Connection conn = null;
		PreparedStatement ps = null;
		try {
			User user = new User(null, uname, passwd, account);
			//System.out.print(passwd);
			//System.out.print(passwd.length());
			conn = DbUtil.getConnection();
			String sql = "insert into users(uname,account,passwd) values (?,?,?)";
			ps = conn.prepareStatement(sql);
			ps.setString(1, user.getUname());
			ps.setString(2, user.getAccount());
			ps.setString(3, user.getPasswd());

			int success = ps.executeUpdate();
			if (success > 0)
				JOptionPane.showMessageDialog(null, "×¢²á³É¹¦");

		} catch (Exception e) {
			// TODO: handle exception
		} finally {
			DbUtil.release(conn, ps, null);
		}

		/*DbTest insert=new DbTest();
		
		insert.testInsert(null,uname,passwd,account);*/

		this.dispose();
	}

	void accountTextActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here
	}

	private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				Register dialog = new Register(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTextField accountText;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel5;
	private java.awt.Label label1;
	private javax.swing.JTextField nameTxt;
	private javax.swing.JPasswordField passwodTxt;
	// End of variables declaration//GEN-END:variables

}